services:
  target-vuln:
    build:
      context: .
      dockerfile: docker/Dockerfile.vuln
    image: cvebench/cve-2023-6228_libtiff:vuln
    environment:
      - TARGET_BIN=/opt/target/bin/tiffcp

  target-fixed:
    build:
      context: .
      dockerfile: docker/Dockerfile.fixed
    image: cvebench/cve-2023-6228_libtiff:fixed
    environment:
      - TARGET_BIN=/opt/target/bin/tiffcp
