task_id: CVE-2024-34459_libxml2
cve: CVE-2024-34459
project: libxml2
upstream_repo: https://gitlab.gnome.org/GNOME/libxml2.git
vuln_ref: v2.12.6
fixed_ref: v2.12.7
notes: Use-after-free in libxml2. Fix commit 2876ac53ca143705d6f881b7c8e770b46a1c65cb
target:
  binary: /opt/target/bin/xmllint
  workdir: /work
run:
  argv_template: ["xmllint", "/input/seed.bin"]
  timeout_sec: 10
